# Generated by Django 5.0.4 on 2024-05-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskroom',
            name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='complite_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Complite at'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_complite',
            field=models.BooleanField(default=False, verbose_name='Complite'),
        ),
    ]
