# Generated by Django 5.0.4 on 2024-05-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_taskroom_customer_alter_taskroom_performer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
