# Generated by Django 5.0.4 on 2024-05-02 09:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_alter_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[\\s\\d\\(\\)-]+$')], verbose_name='Phone number')),
                ('experience', models.IntegerField(default=0, verbose_name='Experience')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='u_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
